language: python
python:
  - "3.6"
before_install:
  - python -m pip install --upgrade pip wheel
install:
  - pip install --progress-bar off -r requirements.txt
  - pip install codecov
env:
  global: COVERAGE=true COV_ARGS="--cov-report xml:coverage.xml"
before_script:
  - make package
script:
  - make lint
  - make docs
  - make test
  - make type-check
after_success:
  - codecov --token=$CODECOV_TOKEN
cache:
  - pip
  - ccache
