[tool.black]
line-length = 88
target-version = ['py36', 'py37']
include = '\.pyi?$'
exclude = '''
    node_modules
  | venv
  | \**/migrations/
  | assets
  | \.pytest_cache
  | \.mypy_cache
  | htmlcov
  | cov_html
  | requirements
'''
