version: "2"

services:
  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    volumes:
      - rainloop_data:/rainloop/data
    depends_on:
      - mail
    ports:
      - "8888:8888"
    environment:
      - LOG_TO_STDOUT=true
  mail:
    # expose ports of mail server to the rainloop container
    expose: ["25", "110", "143", "465", "587", "993", "995"]

volumes:
  rainloop_data:
    driver: local
